"""
AIService — sends an article to Groq's llama-3.3-70b-versatile model and
turns the response into our structured summary shape. Never called on
news fetch; only when the user explicitly asks to simplify an article.
Results are cached by hash(url + "summary") so the same article is never
sent to Groq twice.
"""

import json
import logging

import httpx

from ..config import settings
from ..utils.validators import strip_html, truncate
from .cache_service import cache, make_summary_cache_key

logger = logging.getLogger("finnews.ai_service")

SYSTEM_PROMPT = """You are FinNews AI, an educational financial news simplifier.

Rules:
- Preserve all facts and numbers exactly as given. Never invent data.
- If information is missing, say "Not available in the source."
- Use plain, simple language for beginners.
- Explain every financial term you use.
- NEVER give investment advice, buy/sell/hold recommendations, or predictions.
- Separate facts from interpretation.
- Be concise.

Return ONLY valid JSON matching this schema:
{
  "summary": "2-3 sentence overview",
  "what_happened": "plain description of the event",
  "why_it_matters": "impact on markets/economy/people",
  "key_terms": [{"term": "...", "meaning": "simple definition"}],
  "key_takeaways": ["...", "..."],
  "beginner_explanation": "explain like the reader has zero finance background"
}"""

_CACHE_TTL_SECONDS = 60 * 60 * 24  # 24h

_DEMO_SUMMARY = {
    "summary": (
        "This is a sample AI summary shown in Demo Mode. Add your NewsAPI and Groq API keys "
        "to .env to generate real, article-specific summaries."
    ),
    "what_happened": (
        "In demo mode, FinNews AI shows placeholder text instead of calling the AI model, "
        "so you can see the layout and flow without needing API keys yet."
    ),
    "why_it_matters": (
        "Once real keys are added, this section will explain the practical impact of the actual "
        "article on markets, businesses, or everyday people, in plain language."
    ),
    "key_terms": [
        {"term": "Demo Mode", "meaning": "A fallback state the app uses when API keys are missing, so it still shows something useful."},
        {"term": "AI Summary", "meaning": "A short, plain-language rewrite of a news article generated by a language model."},
    ],
    "key_takeaways": [
        "This summary is sample content, not generated from the real article.",
        "Add NEWS_API_KEY and GROQ_API_KEY to your .env file to enable live summaries.",
    ],
    "beginner_explanation": (
        "Think of this like a placeholder in a magazine layout — it shows you where the real, "
        "AI-written explanation will appear once the app is fully configured."
    ),
}


class AIServiceError(Exception):
    """Raised for AI failures the caller should turn into a friendly message."""


class RateLimitedError(AIServiceError):
    pass


class AIService:
    def __init__(self) -> None:
        self._api_key = settings.groq_api_key
        self._url = settings.groq_api_url
        self._model = settings.groq_model
        self._timeout = settings.groq_api_timeout

    async def summarize(self, title: str, description: str, content: str, url: str) -> dict:
        """Returns a dict matching SummarizeResponse, with cached/demo_mode flags set."""

        if not self._api_key:
            result = dict(_DEMO_SUMMARY)
            result["cached"] = False
            result["demo_mode"] = True
            return result

        cache_key = make_summary_cache_key(url)
        cached_value = cache.get(cache_key)
        if cached_value is not None:
            logger.info("Cache hit for summary (url=%s)", url)
            result = dict(cached_value)
            result["cached"] = True
            result["demo_mode"] = False
            return result

        logger.info("Cache miss for summary (url=%s) — calling Groq", url)
        article_text = self._build_article_text(title, description, content)
        parsed = await self._call_groq(article_text)

        cache.set(cache_key, parsed, ttl=_CACHE_TTL_SECONDS)
        result = dict(parsed)
        result["cached"] = False
        result["demo_mode"] = False
        return result

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _build_article_text(self, title: str, description: str, content: str) -> str:
        clean_title = strip_html(title)
        clean_description = strip_html(description or "")
        clean_content = strip_html(content or "")
        combined = f"Title: {clean_title}\n\nDescription: {clean_description}\n\nContent: {clean_content}"
        return truncate(combined, settings.max_article_chars)

    async def _call_groq(self, article_text: str, _retried: bool = False) -> dict:
        payload = {
            "model": self._model,
            "messages": [
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": article_text},
            ],
            "temperature": 0.3,
            "response_format": {"type": "json_object"},
        }

        try:
            async with httpx.AsyncClient(timeout=self._timeout) as client:
                resp = await client.post(
                    self._url,
                    headers={
                        "Authorization": f"Bearer {self._api_key}",
                        "Content-Type": "application/json",
                    },
                    json=payload,
                )
        except httpx.TimeoutException:
            logger.warning("Groq request timed out")
            raise AIServiceError("AI summarization is temporarily unavailable.")
        except httpx.HTTPError as exc:
            logger.warning("Groq network error: %s", exc)
            raise AIServiceError("AI summarization is temporarily unavailable.")

        if resp.status_code == 429:
            logger.warning("Groq rate limit hit")
            raise RateLimitedError("AI summarization is temporarily unavailable. Please try again shortly.")

        if resp.status_code == 401:
            logger.error("Groq rejected the configured API key")
            raise AIServiceError("API configuration error. Check your environment variables.")

        if 500 <= resp.status_code < 600 and not _retried:
            logger.warning("Groq returned %s — retrying once", resp.status_code)
            return await self._call_groq(article_text, _retried=True)

        if resp.status_code >= 400:
            logger.warning("Groq returned status %s", resp.status_code)
            raise AIServiceError("AI summarization is temporarily unavailable.")

        try:
            data = resp.json()
            raw_content = data["choices"][0]["message"]["content"]
            parsed = json.loads(raw_content)
        except (KeyError, IndexError, ValueError, TypeError) as exc:
            logger.error("Failed to parse Groq response: %s", exc)
            raise AIServiceError("AI summarization is temporarily unavailable.")

        return self._coerce_shape(parsed)

    def _coerce_shape(self, parsed: dict) -> dict:
        """Defensively fill in any fields the model omitted, so the
        response always matches SummarizeResponse."""
        key_terms = parsed.get("key_terms") or []
        safe_key_terms = [
            {"term": str(t.get("term", "")), "meaning": str(t.get("meaning", ""))}
            for t in key_terms
            if isinstance(t, dict)
        ]
        return {
            "summary": str(parsed.get("summary", "")) or "Not available in the source.",
            "what_happened": str(parsed.get("what_happened", "")) or "Not available in the source.",
            "why_it_matters": str(parsed.get("why_it_matters", "")) or "Not available in the source.",
            "key_terms": safe_key_terms,
            "key_takeaways": [str(t) for t in (parsed.get("key_takeaways") or [])],
            "beginner_explanation": str(parsed.get("beginner_explanation", "")) or "Not available in the source.",
        }


ai_service = AIService()
